chore: 🤖 Support dashboard defined override on build

diff --git a/scripts/setup-packaged-app b/scripts/setup-packaged-app
--- a/scripts/setup-packaged-app
+++ b/scripts/setup-packaged-app
@@ -53,4 +53,12 @@ if ! rsync -va "$sourcePath/" "$targetPath"; then
   exit 1
 fi
 
+echo "🤖 Override App defined"
+if ! ./scripts/create-defined-override \
+  "$TARGET_PUBLIC_APP_PATH"; then
+  echo "👹 Oops! Failed to create defined overrides for $TARGET_PUBLIC_APP_PATH for some reason..."
+
+  exit 1
+fi
+
 echo "✅ Completed the $packageName setup!"
