fix: 🐛 missing proxy env var

diff --git a/.github/workflows/commit-checkups.yml b/.github/workflows/commit-checkups.yml
--- a/.github/workflows/commit-checkups.yml
+++ b/.github/workflows/commit-checkups.yml
@@ -7,12 +7,15 @@ on:
       - develop
  pull_request:
 
+
 jobs:
  commit-checkups:
     runs-on: ubuntu-latest
     defaults:
       run:
         shell: bash
+    env:
+      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }} 
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -21,6 +24,26 @@ jobs:
         uses: oven-sh/setup-bun@v2
         with:
           bun-version: latest
+
+      - name: Install Doppler CLI
+        uses: dopplerhq/cli-action@v3
+
+      - name: Setup Doppler
+        run: |
+          doppler configure set token "$DOPPLER_TOKEN"
+
+      - name: Env vars health check
+        run: |
+          if ! doppler run -- printenv | grep -q 'NEXT_PUBLIC_SDK__AUTHENTICATION_URL'; then
+            echo "👹 Oops! Missing required environment variable during health check..."
+            exit 1           
+          fi
+
+          echo "🚑 Doppler envVars seem healthy!"
+
+      - name: Setup dotenv
+        run: |
+          scripts/setup-ci-dotenv
 
       - name: Install dependencies
         run: bun i
